all: equal isint largest sorted


equal: equal.cpp
	g++ -Wall -g -pedantic -o equal equal.cpp

isint: isint.cpp
	g++ -Wall -g -pedantic -o isint isint.cpp

largest: largest.cpp
	g++ -Wall -g -pedantic -o largest largest.cpp

sorted: sorted.cpp
	g++ -Wall -g -pedantic -o sorted sorted.cpp

clean:
	rm -r equal isint largest sorted
